### ISSUE TITLE
LUA errors with addons and interface menu

### ISSUE THREAD

**Issue by Keazra** [wow-rp-addons/XRP#16]
Below is an LUA error I get whenever I open the Interface from the escape menu.

https://pastebin.com/0D4TFSg1

Also, whenever I have TradeskillMaster4 enabled, I seem to get multiple different LUA errors resulting from that (when I get another error from it, I'll paste it here ASAP.)

**Comment by Itarater** [comment]
That Lua error is the same as in #11. It's fixed in the next release.

**Comment by Keazra** [comment]
I now get this LUA error upon starting a character with TSM4 enabled (post 2.0.0 patch):

https://pastebin.com/WQm1NYm1

It doesn't seem to affect anything but it's conflicting with something relating to TradeskillMaster4, for some reason.

**Comment by Itarater** [comment]
That error doesn't appear to have anything to do with TSM4. It looks like it's only showing up in the stack trace due to overwriting the error handler poorly.

It looks like some addon is displaying a tooltip during game load (which is weird, albeit not forbidden), which is triggering a minor bug in XRP's tooltip code that wouldn't normally occur. It won't break anything, and I'll make a couple changes that should fix it in the future for the next release.
