### ISSUE TITLE
Toggle showing images or not

### ISSUE THREAD

**Issue by Drizzard2** [wow-rp-addons/XRP#28]
Hey there.

I love XRP for it's simplicity and such. But some features other addons have would be nice as a default-off option for XRP, like showing images or logo's inserted in the description by TRP users.

**Comment by Solanya** [comment]
Hey, I guess I'll give only one answer for both of your tickets since it boils down to the same issue: I'm not planning on adding new features to XRP. My involvement is limited to making sure the addon keeps running despite patch or RP protocol changes, until someone else wishes to take it over. I don't have the time to work on it besides that. ^^
